"""Specialist modules. Hand-written: generalist. Everything else is generated by the Forge."""

from __future__ import annotations

import importlib
import pkgutil
import re
from types import ModuleType

from bloom.specs import module_name

_FINAL_RE = re.compile(r"FINAL:\s*(.+)", re.IGNORECASE)


def default_postprocess(text: str) -> str | None:
    matches = _FINAL_RE.findall(text or "")
    return matches[-1].strip().strip("`*").strip() if matches else None


def load_specialist(slug: str) -> ModuleType | None:
    importlib.invalidate_caches()
    try:
        return importlib.import_module(f"{__name__}.{module_name(slug)}")
    except ModuleNotFoundError:
        return None


def list_specialists() -> list[str]:
    return sorted(m.name.replace("_", "-") for m in pkgutil.iter_modules(__path__))


def spec_from_module(mod: ModuleType) -> dict:
    return {
        "slug": mod.SLUG,
        "category": getattr(mod, "CATEGORY", None),
        "purpose": getattr(mod, "PURPOSE", ""),
        "instructions": mod.INSTRUCTIONS,
        "model": mod.MODEL,
        "tools": list(mod.TOOLS),
        "examples": list(getattr(mod, "EXAMPLES", [])),
        "verify": getattr(mod, "VERIFY", ""),
    }
