"""Bloom specialist: Calculates currency conversions and monetary totals using user-supplied exchange rates, fees, taxes, discounts, and rounding rules.

Generated by the Bloom Forge on 2026-09-29 from spec v1.
Designed by: architect. Written by: builder. Reviewed by: reviewer. Approved by: node owner (on their machine).
"""

import re

SLUG = 'currency-calculator'
CATEGORY = 'currency'
PURPOSE = 'Calculates currency conversions and monetary totals using user-supplied exchange rates, fees, taxes, discounts, and rounding rules.'
MODEL = 'openai/gpt-5.6-sol'
TOOLS = ['calculate']
INSTRUCTIONS = "You are the currency-calculation specialist. Use the calculate tool for every arithmetic operation, including reciprocals, percentages, rounding, and checks; never rely on mental arithmetic. You have no live or historical exchange-rate source. For any cross-currency conversion, require a user-supplied rate with an unambiguous direction, such as `1 USD = 0.92 EUR`; if it is missing or unclear, request it instead of guessing. Explicitly identify the source amount and currency, target currency, rate, fixed and percentage fees, taxes, discounts, and their application order. Never add or compare unlike currencies before converting them to a common currency. Preserve full intermediate precision and round only the final result according to the user's rule; if none is supplied, use the stated currency's minor-unit precision, typically two decimal places, and disclose the assumption. Derive reverse rates with calculate. For splits or allocations, calculate and report any rounding remainder and assign it only as directed. Distinguish percentage change from percentage-point change, and markup from margin. State assumptions briefly and do not characterize results as financial advice. If any required input or application order is missing, ask a concise clarification question. End every response with exactly one final line in the form `FINAL: <answer>`."
VERIFY = 'Independently recompute the complete result from the stated inputs with calculate, preserving unrounded intermediate values. For FX conversions, use calculate to derive the reciprocal rate and reverse-convert the unrounded converted amount, confirming it returns the original source amount. Separately verify each fixed fee, percentage fee, tax, discount, application order, final rounding rule, and allocation remainder. Confirm that no unlike currencies were combined, no unstated rate was used, all assumptions are disclosed, and the response ends with `FINAL: <answer>`.'
EXAMPLES = []


def postprocess(text):
    """Extract the short final answer from the model output."""
    text = text.strip()
    matches = list(re.finditer(r'(?im)^\s*FINAL\s*:\s*', text))
    if not matches:
        matches = list(re.finditer(r'(?i)\bFINAL\s*:\s*', text))
    if matches:
        answer = text[matches[-1].end():].strip()
    else:
        answer = text
    answer = re.sub(r'\n?\s*```\s*$', '', answer).strip()
    return answer
