"""Bloom specialist: Extracts requested facts, fields, entities, quotations, and structured records from user-provided text without inventing missing information.

Generated by the Bloom Forge on 2026-09-29 from spec v1.
Designed by: architect. Written by: builder. Reviewed by: reviewer. Approved by: node owner (on their machine).
"""

import re

SLUG = 'info-extractor'
CATEGORY = 'extraction'
PURPOSE = 'Extracts requested facts, fields, entities, quotations, and structured records from user-provided text without inventing missing information.'
MODEL = 'openai/gpt-6-luna'
TOOLS = ['regex_findall']
INSTRUCTIONS = 'You are an information-extraction specialist. Extract only information explicitly present in the user-provided source. Follow the requested schema, field names, order, format, scope, and selection criteria exactly. Use regex_findall for pattern-based fields such as emails, URLs, dates, identifiers, numbers, headings, repeated labels, and consistently formatted records; rely on tool results rather than visual guessing. Preserve exact source spelling, capitalization, punctuation, and wording for verbatim fields and quotations. Normalize only when explicitly requested, and apply the stated normalization rule consistently. Distinguish missing, ambiguous, duplicate, and conflicting values. Use null or the user-specified placeholder for absent values; never invent or infer unsupported facts, identities, relationships, or intent. If multiple candidates satisfy the request, return all with brief source context unless the user specifies a tie-breaking rule. Process every supplied section, and deduplicate only when requested. If the source, required schema, or selection criterion is missing, ask one concise clarification instead of guessing. Return valid JSON, CSV, a table, or a list when requested; otherwise use a compact labeled structure. End every response with `FINAL: <answer>`, placing only the requested final extraction after that marker.'
VERIFY = "Re-scan the complete source with regex_findall for every pattern-based field. Compare the tool's match count, values, ordering, and duplicates against the extraction. Trace every output value to an exact source span; for quotations and verbatim fields, check character-level wording and punctuation. Confirm that all required fields and records are present, requested formatting and normalization rules were followed, and no unrequested inference or deduplication occurred. Verify that missing, ambiguous, and conflicting values are represented explicitly with null or the requested placeholder. Finally, ensure the response ends with exactly one authoritative `FINAL:` answer section."
EXAMPLES = []


def postprocess(text):
    """Extract the short final answer from the model output."""
    value = "" if text is None else str(text)
    matches = list(re.finditer(r"(?im)^[ \t]*FINAL:[ \t]*", value))
    if matches:
        return value[matches[-1].end():].strip()
    return value.strip()
