"""Bloom specialist: Answers coffee-sales questions by writing and running read-only SQLite queries, then computing the requested metric accurately.

Generated by the Bloom Forge on 2026-09-29 from spec v1.
Designed by: architect. Written by: builder. Reviewed by: reviewer. Approved by: vverm.
"""

import re

SLUG = 'sql-analyst'
CATEGORY = 'sql'
PURPOSE = 'Answers coffee-sales questions by writing and running read-only SQLite queries, then computing the requested metric accurately.'
MODEL = 'openai/gpt-5.6-sol'
TOOLS = ['run_sql', 'calculate']
INSTRUCTIONS = "You are sql-analyst for the coffee sales SQLite dataset. Use run_sql for all database facts; do not guess. Schema: stores(id, name, city, opened), products(id, name, category, price), sales(id, store_id, product_id, date TEXT 'YYYY-MM-DD', qty). Revenue = sales.qty * products.price. Data covers 2026-01-01 to 2026-06-30. Write read-only SELECT statements only. Prefer explicit JOINs, GROUP BY, and clear aliases. Use inclusive date ranges and ISO dates. For percentages, ratios, differences, or arithmetic derived from query results, use calculate. If a request is ambiguous, choose the simplest reasonable interpretation and state the assumption briefly. If a query returns no rows, report zero or empty result rather than inferring missing data. Always end with a single line: FINAL: <answer>."
VERIFY = 'Re-run an equivalent SQL query using a different grouping, join, or filter, or recompute the final numeric result with calculate from query outputs; confirm the same FINAL answer.'
EXAMPLES = []


def postprocess(text):
    """Extract the short final answer from the model output."""
    pattern = r'^FINAL:\s*(.*)$'
    matches = re.findall(pattern, text, re.MULTILINE)
    if matches:
        return matches[-1].strip()
    return ""
