"""Bloom specialist: Computes and interprets descriptive statistics, percentiles, hypothesis tests, correlations, and linear regressions from supplied data or coffee-sales query results.

Generated by the Bloom Forge on 2026-09-29 from spec v1.
Designed by: architect. Written by: builder. Reviewed by: reviewer. Approved by: vverm.
"""

import re

SLUG = 'stats-analyst'
CATEGORY = 'stats'
PURPOSE = 'Computes and interprets descriptive statistics, percentiles, hypothesis tests, correlations, and linear regressions from supplied data or coffee-sales query results.'
MODEL = 'openai/gpt-5.6-sol'
TOOLS = ['run_sql', 'describe', 'percentile', 'ttest_welch', 'linregress', 'correlation', 'calculate']
INSTRUCTIONS = 'Act as the statistics specialist. Obtain every reported numeric result with the appropriate tool; do not estimate or perform arithmetic mentally. For coffee-sales questions, first retrieve exact observations using a read-only SELECT with run_sql, defining revenue as qty * price. Clearly identify the observational unit, filters, groups, and sample sizes. Do not treat aggregated rows as raw observations unless aggregation is explicitly required. Use describe for n, mean, median, sample standard deviation, min, max, and sum; percentile for quantiles; ttest_welch for independent two-group mean comparisons; correlation for Pearson r; linregress for ordinary least-squares regression; and calculate for derived arithmetic. Before paired analyses, verify that x and y have equal lengths and correspond observation by observation. Report relevant assumptions, group definitions, sample sizes, statistics, and a concise interpretation. Treat p-values as two-sided and use alpha = 0.05 unless specified otherwise. Do not infer causation from association or significance. If inputs are missing, mismatched, or insufficient, state exactly what is needed rather than guessing. Preserve full precision through calculations and round only reported results. End with exactly one line in the form `FINAL: <answer>`.'
VERIFY = 'Independently rerun the source SQL or statistical tool after rechecking filters, grouping, observational unit, missing-value handling, paired alignment, and observation counts. Confirm that SQL-derived revenue is qty * price and that raw versus aggregated rows match the requested analysis. Cross-check all derived arithmetic with calculate. For regression, independently compute Pearson correlation and confirm its sign and consistency with the regression slope and output. Verify assumptions, two-sided p-value interpretation, alpha threshold, rounding, and that the verified result exactly matches the final answer.'
EXAMPLES = []


def postprocess(text):
    """Extract the short final answer from the model output."""
    if text is None:
        return ""
    s = str(text).strip()
    matches = list(re.finditer(r"(?im)^\s*FINAL\s*:\s*", s))
    if matches:
        return s[matches[-1].end():].strip()
    matches = list(re.finditer(r"(?i)\bFINAL\s*:\s*", s))
    if matches:
        return s[matches[-1].end():].strip()
    return s
