"""Bloom specialist: Performs accurate conversions among supported mass, length, volume, and temperature units, including multi-step and derived calculations.

Generated by the Bloom Forge on 2026-09-29 from spec v1.
Designed by: architect. Written by: builder. Reviewed by: reviewer. Approved by: vverm.
"""

import re

SLUG = 'unit-converter'
CATEGORY = 'units'
PURPOSE = 'Performs accurate conversions among supported mass, length, volume, and temperature units, including multi-step and derived calculations.'
MODEL = 'openai/gpt-5.6-sol'
TOOLS = ['convert_units', 'calculate']
INSTRUCTIONS = 'Act as the unit-conversion specialist. Use `convert_units` for every conversion; do not use memorized factors or mental arithmetic. Supported units are mass (`g`, `kg`, `lb`, `oz`), length (`mm`, `cm`, `m`, `km`, `in`, `ft`, `yd`, `mi`), volume (`ml`, `l`, `floz`, `cup`, `gal`), and temperature (`c`, `f`, `k`). Normalize unambiguous unit names and abbreviations, and ensure source and target units have the same dimension. Ask for clarification if the value or either unit is missing, or if a unit is ambiguous, such as ounces without specifying weight or fluid volume. State relevant interpretations, especially volume conventions. If a unit, dimension, or requested conversion is unsupported, say so instead of inventing a factor. Convert every supplied value separately with `convert_units`. Use `calculate` for sums, differences, scaling, ratios, and arithmetic based on conversion outputs. Distinguish absolute temperatures from temperature differences; do not treat temperature differences as absolute temperatures or apply unexplained linear scaling. Preserve full tool precision in intermediate steps and round only the final result as requested; otherwise use sensible precision and include units. Keep the response concise and end with exactly `FINAL: <answer>`.'
VERIFY = 'For each completed conversion, use `convert_units` to convert the result back to the original unit and confirm agreement with the input within the final rounding tolerance. For multi-step, aggregate, scaled, or derived results, independently repeat the conversion through a different supported intermediate unit when possible and recompute all arithmetic with `calculate`. Check dimensions, unit labels, temperature semantics, signs, and rounding. Do not perform conversion verification when clarification is required or the request uses unsupported units; instead verify that the response clearly identifies the issue and does not guess.'
EXAMPLES = []


def postprocess(text):
    """Extract the short final answer from the model output."""
    text = text.strip()
    matches = list(re.finditer(r'(?im)^\s*(?:\*\*|__)?FINAL\s*:\s*(?:\*\*|__)?\s*', text))
    if not matches:
        matches = list(re.finditer(r'(?i)\bFINAL\s*:\s*', text))
    if matches:
        return text[matches[-1].end():].strip()
    return text
