"""Spawn a specialist AgentApp from the bloom-test-hello template.

Copies the template, turns it into a specialist (new name, description,
system instructions, optional model), builds a FAB, shows the diff, scans
for secrets, and only publishes to Flower Hub after an explicit "y".

Usage:
    uv run python scripts/spawn_test.py                 # SQL specialist, asks before publish
    uv run python scripts/spawn_test.py --no-publish    # stop after build + diff
"""

from __future__ import annotations

import argparse
import difflib
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "templates" / "flower" / "agent"  # copy of @flwrlabs/agent (== bloom-test-hello)
OUT_ROOT = ROOT.parent / "bloom-agents"  # outside the repo: `flwr app publish` uploads the whole dir

# Files copied from the template. Everything else (.venv, uv.lock, *.fab,
# __pycache__, this script) is left behind.
COPY = ["agent/__init__.py", "agent/agent_app.py", "pyproject.toml", "LICENSE", ".gitignore"]

SQL_SPEC = {
    "name": "bloom-test-sql",
    "description": "Bloom specialist: writes and explains SQL queries",
    "model": None,  # None = keep the template's model
    "instructions": (
        "You are a SQL specialist in the Bloom agent team. Given a question and "
        "a table schema, write one correct, minimal SQLite query that answers it. "
        "Return the query in a ```sql block, then one sentence explaining it. "
        "If the schema is missing, state the assumptions you made."
    ),
}

# Credential-looking strings that must never ship in a published app.
SECRET_PATTERNS = [
    r"sk-[A-Za-z0-9_\-]{16,}",
    r"(?i)(api[_-]?key|secret|token|password)\s*=\s*['\"][^'\"]{8,}['\"]",
    r"AKIA[0-9A-Z]{16}",
    r"ghp_[A-Za-z0-9]{20,}",
]


def sub_once(pattern: str, repl: str, text: str, what: str) -> str:
    """Regex-substitute exactly once, or fail loudly if the template changed."""
    new, n = re.subn(pattern, repl, text, count=1, flags=re.MULTILINE)
    if n != 1:
        sys.exit(f"ERROR: template no longer matches pattern for {what!r}: {pattern}")
    return new


def patch_agent_app(src: str, spec: dict) -> str:
    src = sub_once(
        r'^"""A minimal Flower AgentApp\."""',
        f'"""{spec["description"]}."""',
        src,
        "module docstring",
    )
    if spec["model"]:
        src = sub_once(r'^MODEL = ".*"$', f'MODEL = "{spec["model"]}"', src, "MODEL")
    src = sub_once(
        r'^(MODEL = ".*"\n)',
        r"\1" + f"INSTRUCTIONS = {spec['instructions']!r}\n",
        src,
        "INSTRUCTIONS insertion",
    )
    src = sub_once(
        r"^(\s*)input=agent\.prompt,$",
        r"\1instructions=INSTRUCTIONS,\n\1input=agent.prompt,",
        src,
        "instructions kwarg",
    )
    return src


def patch_pyproject(src: str, spec: dict) -> str:
    src = sub_once(r'^name = ".*"$', f'name = "{spec["name"]}"', src, "name")
    src = sub_once(r'^version = ".*"$', 'version = "0.1.0"', src, "version")
    src = sub_once(
        r'^description = ".*"$', f'description = "{spec["description"]}"', src, "description"
    )
    return src


def readme(spec: dict) -> str:
    return (
        "---\ntags: [agentapp]\ndataset: []\nframework: []\n---\n\n"
        f"# {spec['name']}\n\n{spec['description']}.\n\n"
        "Generated by Bloom's Forge from the `@vverm/bloom-test-hello` template.\n\n"
        f"## System instructions\n\n> {spec['instructions']}\n"
    )


def show_diff(out: Path) -> None:
    for rel in ["agent/agent_app.py", "pyproject.toml"]:
        a = (TEMPLATE / rel).read_text().splitlines(keepends=True)
        b = (out / rel).read_text().splitlines(keepends=True)
        sys.stdout.writelines(
            difflib.unified_diff(a, b, f"template/{rel}", f"{out.name}/{rel}")
        )
    print(f"+++ new file {out.name}/README.md")


def scan_secrets(out: Path) -> list[str]:
    hits = []
    for f in out.rglob("*"):
        if f.is_file() and f.suffix in {".py", ".toml", ".md", ".json", ".txt", ".yaml", ".yml"}:
            text = f.read_text(errors="ignore")
            for pat in SECRET_PATTERNS:
                for m in re.finditer(pat, text):
                    hits.append(f"{f.relative_to(out)}: {m.group(0)[:12]}...")
    return hits


def flwr(*args: str, cwd: Path) -> None:
    # Reuse the repo's environment so the new project needs no uv sync.
    cmd = ["uv", "run", "--project", str(ROOT), "flwr", *args]
    print("$", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-publish", action="store_true")
    args = parser.parse_args()
    spec = SQL_SPEC

    if not spec["name"].startswith("bloom-test-"):
        sys.exit("ERROR: test agents must be named bloom-test-* ('bloom' is reserved).")

    out = OUT_ROOT / spec["name"]
    if out.exists():
        sys.exit(f"ERROR: {out} already exists; remove it or pick another name.")
    for rel in COPY:
        (out / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(TEMPLATE / rel, out / rel)

    app_py = out / "agent/agent_app.py"
    app_py.write_text(patch_agent_app(app_py.read_text(), spec))
    pyproject = out / "pyproject.toml"
    pyproject.write_text(patch_pyproject(pyproject.read_text(), spec))
    (out / "README.md").write_text(readme(spec))
    compile(app_py.read_text(), str(app_py), "exec")  # syntax check
    print(f"Created {out}\n")

    flwr("build", cwd=out)
    print()
    show_diff(out)

    hits = scan_secrets(out)
    if hits:
        print("\nPossible secrets found, refusing to publish:\n  " + "\n  ".join(hits))
        sys.exit(1)
    print("\nSecret scan: clean.")

    if args.no_publish:
        print("--no-publish set; stopping before publish.")
        return
    answer = input(f"\nPublish @vverm/{spec['name']} to Flower Hub (PUBLIC, immediate)? [y/N] ")
    if answer.strip().lower() != "y":
        print("Not published.")
        return
    flwr("app", "publish", ".", cwd=out)


if __name__ == "__main__":
    main()
